### ISSUE TITLE
deleteOthers before inserting

### ISSUE THREAD

**Issue by Munksgaard** [mlipscombe/postgraphile-plugin-nested-mutations#15]
I have two tables `foo` and `bar`, with `foo` having a unique reference to `bar`. If I update a reference like below, the query fails, and I think it is because the `create` portion is executed before the `deleteOthers` portion. Is that really the case, and if so, is that on purpose?

```graphql
mutation {
  updateFooById(
    input: {
      fooPatch: {
        fooBarUsingId: {
          create: [
            { barId: 15, value: 123412344 }
          ]
          deleteOthers:true
        }
      }
      id: 14
    }
  ) {
    foo {
      id
    }
  }
}
```

**Comment by srp** [comment]
If you run postgraphile with the environment variable `DEBUG="postgraphile:postgres"` set, it should log all the queries out to the console so you can see exactly what it looks like.

**Comment by rychoo2** [comment]
Hi, nice plugin. I have the same problem. Looking forward to this pull request being merged.

**Comment by mlipscombe** [comment]
The proposed fix breaks the logic.  The idea is `deleteOthers` is that anything that is not 'touched' will be deleted, to allow updating nested rows atomically. New rows can be created via any unique key, and so we don't necessarily know the PK of those rows until they are inserted.

I think there are two more ideal ways to handle the case where you want to delete everything first -- either use a `deleteX` mutation first, or we can implement an `upsert` field in addition to `create` and `update`.

If you don't think either of these will work, can you give me a bit more info about your use case?

**Comment by Munksgaard** [comment]
Would the `upsert` field then delete any rows that weren't updated? I'm not quite sure I understand how that would work. Manually using a deleteX mutation first could probably work, but it feels a bit circuitous, especially because the `deleteOthers` field is already there.

**Comment by Munksgaard** [comment]
Another solution would simply be to specify in documentation for the `deleteOthers` field, that it only deletes other entries _after_ inserting, meaning that it won't handle uniqueness constraints gracefully.

**Comment by erkieh** [comment]
Hi @Munksgaard!
@madflow has released a version with fixed parenthesis wrapping. Would be great if he got this delete others order fix in there and released as well.

https://github.com/priotas/postgraphile-plugin-nested-mutations/compare/master...Munksgaard:patch-1?expand=1
