### ISSUE TITLE
support for @omit?

### ISSUE THREAD

**Issue by edclement** [mlipscombe/postgraphile-plugin-nested-mutations#3]
Is there anyway currently to prevent (omit) a nested mutation from appearing within the schema of certain parent mutations?

**Comment by mlipscombe** [comment]
Right now, a nested mutation field will only be omitted if the foreign key itself has an `@omit` comment, or if any of the keys (on either side of the relationship) that make up the foreign key have `@omit` on them.  If any of the keys have an `@omit create`, then the create field won't be present.

What is your use case for omitting them?  Is it just to prevent clutter, or something more?  I guess it would be possible to add a smart comment check on the parent table for a list of omitted nested mutations, something like `@omitNested` with a comma separated list of fields to omit.

**Comment by edclement** [comment]
Interesting, I'm not seeing the behavior you describe using `@omit create` with my schema. I'll try to test it with a simplified version and post the schema here as soon as I have time.

**Comment by mlipscombe** [comment]
I'm unable to duplicate this.  In my tests `@omit create` prevents any node having the `create` field. I'm closing this for now, but if you have an example that triggers a problem, please feel free to reopen.
