### ISSUE TITLE
Repo status

### ISSUE THREAD

**Issue by madflow** [mlipscombe/postgraphile-plugin-nested-mutations#32]
Hi @mlipscombe!

Thank you for creating this valuable plugin! Is it fair to say that you do no actively maintain this repo for public usage anymore?

I just tried to use it for our application and I immediately got bit by https://github.com/mlipscombe/postgraphile-plugin-nested-mutations/issues/15. When I tried to use the proposed workaround and call `deleteByX` first - the plugin created a syntax error (#31).

It would be nice to know if you are planning on maintaining PR etc. in the future or if I should go fork myself (which is totally fine).

Florian

**Comment by sstubbs** [comment]
Yes this is a great plugin. I would also like to know this. There seem to quite a few forks of it. I am happy to contribute to a fork of it but have no idea which one to look at.

**Comment by jarvisuser90** [comment]
I agree. It's a great plugin. Is this repo still being maintained?

**Comment by mlipscombe** [comment]
Sorry for disappearing.  I've picked up development on this plugin again, and I'll be making a new release with some of the PRs merged.

**Comment by bklever** [comment]
any chance of that new release?
