### ISSUE TITLE
Multiple instances of GraphQLSchema

### ISSUE THREAD

**Issue by Tycholiz** [mlipscombe/postgraphile-plugin-nested-mutations#39]
I am using this module as a library, and I follow the instruction installations, but notice that my Graphiql Explorer is empty, and there is this error in the console:

>Error: Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.

>Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

>https://yarnpkg.com/en/docs/selective-version-resolutions

>Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.

Any insight on this issue?

**Comment by mlipscombe** [comment]
Sorry for the delay.  For the fix, see here:
https://typegraphql.com/docs/faq.html#how-do-i-fix-this-error-cannot-use-graphqlschema-object-object-from-another-module-or-realm
