### ISSUE TITLE
Missing relationships from tables with multiple foreign-keys to the same related table

### ISSUE THREAD

**Issue by furious-luke** [mlipscombe/postgraphile-plugin-nested-mutations#9]
Hi there, thanks for making a great plugin for PostGraphile, it's very useful.

I've noticed that when I use the plugin for tables that contain multiple connections to the same related table, only one of the reverse connections appears as a possible input to the mutation. As an example consider the following tables that might be used to represent a job and a relationship between jobs:

```sql
create table job (
  id serial primary key,
);

create table job_relationship (
  type text,
  from_job_id integer references job(id),
  to_job_id integer references job(id)
);
```

In this scenario, the GraphQL type produced for creating a "job" would include the reverse input for the "to_job_id" relationship only; the "from_job_id" input is not available.

**Comment by furious-luke** [comment]
With a little tinkering I can see that I can get both reverse relationships if I change line 69 from this:

```js
          : reverseMutationName || inflection.camelCase(`${inflection.pluralize(tableFieldName)}_using_${foreignKeyNames.join('_and_')}`);
```

to this:

```js
          : reverseMutationName || inflection.camelCase(`${inflection.pluralize(tableFieldName)}_using_${keyNames.join('_and_')}`);
```

The change is using `keyNames` instead of `foreignKeyNames`. It seems that using `foreignKeyNames` tends to result in using the `id` column of the table to which the reverses are going, in this case that's the `job` table. So, both reverse fields are trying to both be called `jobRelationshipsUsingId`, and they're stomping on one another. By using `keyNames`, the reverse fields are called `jobRelationshipsUsingFromId` and `jobRelationshipsUsingToId`.

I'm not sure if the above solution is actually the right solutions, and even if it is it's a pretty major change in that all the reverse fields now have a new default naming scheme. In any case, I hope this helps resolve the issue.

**Comment by mlipscombe** [comment]
I think the correct fix for this scenario is actually to generate names that are something like `jobRelationshipsIntoToIdUsingId` and `jobRelationshipsIntoFromIdUsingId` (ain't that a mouthful!?).  

I'll have a think about how to handle this better, but in the meanwhile, you can use smart comments to set the names so they don't conflict -- using `@forwardMutationName` and `@reverseMutationName`:

https://github.com/mlipscombe/postgraphile-plugin-nested-mutations#smart-comments

**Comment by mlipscombe** [comment]
This should be fixed in the latest version.  Tables that have multiple FKs between them should now generate field names that include the key fields.  Feel free to reopen if anything isn't working right.

**Comment by furious-luke** [comment]
Fantastic, thanks very much!
